language: c

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - automake
            - autoconf
            - gdb
            - libtool
            - autotools-dev


matrix:
    exclude:
        - compiler: "gcc"
        - compiler: "clang"
    include:
        - compiler: "gcc"
          env: CFLAGS="-g -O2 -Wall"
        - compiler: "clang"
          env: CFLAGS="-g -O2 -Wall"

script:
    - tests/travis/run.sh
